# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1667, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(602, 602))
        self.frame_3.setMaximumSize(QtCore.QSize(602, 602))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_vtkPlane = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_vtkPlane.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_vtkPlane.setObjectName("horizontalLayout_vtkPlane")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color:rgb(255,0,0)")
        self.label_38.setObjectName("label_38")
        self.horizontalLayout.addWidget(self.label_38)
        self.horizontalScrollBar_spinCenterX_vtk = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_spinCenterX_vtk.setTracking(True)
        self.horizontalScrollBar_spinCenterX_vtk.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_spinCenterX_vtk.setInvertedAppearance(False)
        self.horizontalScrollBar_spinCenterX_vtk.setInvertedControls(False)
        self.horizontalScrollBar_spinCenterX_vtk.setObjectName("horizontalScrollBar_spinCenterX_vtk")
        self.horizontalLayout.addWidget(self.horizontalScrollBar_spinCenterX_vtk)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:rgb(0,255,0)")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_2.addWidget(self.label_39)
        self.horizontalScrollBar_spinCenterY_vtk = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_spinCenterY_vtk.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_spinCenterY_vtk.setInvertedAppearance(False)
        self.horizontalScrollBar_spinCenterY_vtk.setInvertedControls(False)
        self.horizontalScrollBar_spinCenterY_vtk.setObjectName("horizontalScrollBar_spinCenterY_vtk")
        self.horizontalLayout_2.addWidget(self.horizontalScrollBar_spinCenterY_vtk)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color:rgb(0,0,255)")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_9.addWidget(self.label_46)
        self.horizontalScrollBar_spinCenterZ_vtk = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_spinCenterZ_vtk.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_spinCenterZ_vtk.setInvertedAppearance(False)
        self.horizontalScrollBar_spinCenterZ_vtk.setInvertedControls(False)
        self.horizontalScrollBar_spinCenterZ_vtk.setObjectName("horizontalScrollBar_spinCenterZ_vtk")
        self.horizontalLayout_9.addWidget(self.horizontalScrollBar_spinCenterZ_vtk)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_imagePath = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_imagePath.setEnabled(False)
        self.lineEdit_imagePath.setObjectName("lineEdit_imagePath")
        self.verticalLayout_10.addWidget(self.lineEdit_imagePath)
        self.lineEdit_labelPath = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_labelPath.setEnabled(False)
        self.lineEdit_labelPath.setObjectName("lineEdit_labelPath")
        self.verticalLayout_10.addWidget(self.lineEdit_labelPath)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.AutoText)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_34 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color:rgb(255,0,0)")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_15.addWidget(self.label_34)
        self.spinBox_LVA_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_LVA_X.setObjectName("spinBox_LVA_X")
        self.horizontalLayout_15.addWidget(self.spinBox_LVA_X)
        self.horizontalSlider_LVA_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_LVA_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LVA_X.setObjectName("horizontalSlider_LVA_X")
        self.horizontalLayout_15.addWidget(self.horizontalSlider_LVA_X)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_35 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:rgb(0,255,0)")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_16.addWidget(self.label_35)
        self.spinBox_LVA_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_LVA_Y.setObjectName("spinBox_LVA_Y")
        self.horizontalLayout_16.addWidget(self.spinBox_LVA_Y)
        self.horizontalSlider_LVA_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_LVA_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LVA_Y.setObjectName("horizontalSlider_LVA_Y")
        self.horizontalLayout_16.addWidget(self.horizontalSlider_LVA_Y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_36 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:rgb(0,0,255)")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_17.addWidget(self.label_36)
        self.spinBox_LVA_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_LVA_Z.setObjectName("spinBox_LVA_Z")
        self.horizontalLayout_17.addWidget(self.spinBox_LVA_Z)
        self.horizontalSlider_LVA_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_LVA_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LVA_Z.setObjectName("horizontalSlider_LVA_Z")
        self.horizontalLayout_17.addWidget(self.horizontalSlider_LVA_Z)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_37 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:rgb(255,0,0)")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_18.addWidget(self.label_37)
        self.spinBox_RVA_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_RVA_X.setObjectName("spinBox_RVA_X")
        self.horizontalLayout_18.addWidget(self.spinBox_RVA_X)
        self.horizontalSlider_RVA_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_RVA_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_RVA_X.setObjectName("horizontalSlider_RVA_X")
        self.horizontalLayout_18.addWidget(self.horizontalSlider_RVA_X)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_40 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:rgb(0,255,0)")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_19.addWidget(self.label_40)
        self.spinBox_RVA_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_RVA_Y.setObjectName("spinBox_RVA_Y")
        self.horizontalLayout_19.addWidget(self.spinBox_RVA_Y)
        self.horizontalSlider_RVA_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_RVA_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_RVA_Y.setObjectName("horizontalSlider_RVA_Y")
        self.horizontalLayout_19.addWidget(self.horizontalSlider_RVA_Y)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_41 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color:rgb(0,0,255)")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_20.addWidget(self.label_41)
        self.spinBox_RVA_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_RVA_Z.setObjectName("spinBox_RVA_Z")
        self.horizontalLayout_20.addWidget(self.spinBox_RVA_Z)
        self.horizontalSlider_RVA_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_RVA_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_RVA_Z.setObjectName("horizontalSlider_RVA_Z")
        self.horizontalLayout_20.addWidget(self.horizontalSlider_RVA_Z)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_19 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.label_19)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_45 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:rgb(255,0,0)")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_24.addWidget(self.label_45)
        self.spinBox_AV_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_AV_X.setObjectName("spinBox_AV_X")
        self.horizontalLayout_24.addWidget(self.spinBox_AV_X)
        self.horizontalSlider_AV_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_AV_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AV_X.setObjectName("horizontalSlider_AV_X")
        self.horizontalLayout_24.addWidget(self.horizontalSlider_AV_X)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_48 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color:rgb(0,255,0)")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_25.addWidget(self.label_48)
        self.spinBox_AV_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_AV_Y.setObjectName("spinBox_AV_Y")
        self.horizontalLayout_25.addWidget(self.spinBox_AV_Y)
        self.horizontalSlider_AV_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_AV_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AV_Y.setObjectName("horizontalSlider_AV_Y")
        self.horizontalLayout_25.addWidget(self.horizontalSlider_AV_Y)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_50 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color:rgb(0,0,255)")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_26.addWidget(self.label_50)
        self.spinBox_AV_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_AV_Z.setObjectName("spinBox_AV_Z")
        self.horizontalLayout_26.addWidget(self.spinBox_AV_Z)
        self.horizontalSlider_AV_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_AV_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AV_Z.setObjectName("horizontalSlider_AV_Z")
        self.horizontalLayout_26.addWidget(self.horizontalSlider_AV_Z)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_13.addWidget(self.line_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_42 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color:rgb(255,0,0)")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_21.addWidget(self.label_42)
        self.spinBox_PV_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_PV_X.setObjectName("spinBox_PV_X")
        self.horizontalLayout_21.addWidget(self.spinBox_PV_X)
        self.horizontalSlider_PV_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_PV_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_PV_X.setObjectName("horizontalSlider_PV_X")
        self.horizontalLayout_21.addWidget(self.horizontalSlider_PV_X)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_43 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color:rgb(0,255,0)")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_22.addWidget(self.label_43)
        self.spinBox_PV_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_PV_Y.setObjectName("spinBox_PV_Y")
        self.horizontalLayout_22.addWidget(self.spinBox_PV_Y)
        self.horizontalSlider_PV_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_PV_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_PV_Y.setObjectName("horizontalSlider_PV_Y")
        self.horizontalLayout_22.addWidget(self.horizontalSlider_PV_Y)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_44 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("color:rgb(0,0,255)")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_23.addWidget(self.label_44)
        self.spinBox_PV_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_PV_Z.setObjectName("spinBox_PV_Z")
        self.horizontalLayout_23.addWidget(self.spinBox_PV_Z)
        self.horizontalSlider_PV_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_PV_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_PV_Z.setObjectName("horizontalSlider_PV_Z")
        self.horizontalLayout_23.addWidget(self.horizontalSlider_PV_Z)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_8.addWidget(self.line_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_20 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_14.addWidget(self.label_20)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_52 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("color:rgb(255,0,0)")
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_27.addWidget(self.label_52)
        self.spinBox_MV_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_MV_X.setObjectName("spinBox_MV_X")
        self.horizontalLayout_27.addWidget(self.spinBox_MV_X)
        self.horizontalSlider_MV_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_MV_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_MV_X.setObjectName("horizontalSlider_MV_X")
        self.horizontalLayout_27.addWidget(self.horizontalSlider_MV_X)
        self.verticalLayout_14.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_53 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color:rgb(0,255,0)")
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_28.addWidget(self.label_53)
        self.spinBox_MV_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_MV_Y.setObjectName("spinBox_MV_Y")
        self.horizontalLayout_28.addWidget(self.spinBox_MV_Y)
        self.horizontalSlider_MV_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_MV_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_MV_Y.setObjectName("horizontalSlider_MV_Y")
        self.horizontalLayout_28.addWidget(self.horizontalSlider_MV_Y)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_54 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("color:rgb(0,0,255)")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_29.addWidget(self.label_54)
        self.spinBox_MV_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_MV_Z.setObjectName("spinBox_MV_Z")
        self.horizontalLayout_29.addWidget(self.spinBox_MV_Z)
        self.horizontalSlider_MV_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_MV_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_MV_Z.setObjectName("horizontalSlider_MV_Z")
        self.horizontalLayout_29.addWidget(self.horizontalSlider_MV_Z)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_14.addWidget(self.line_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_21 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_15.addWidget(self.label_21)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_55 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color:rgb(255,0,0)")
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_30.addWidget(self.label_55)
        self.spinBox_TV_X = QtWidgets.QSpinBox(self.frame)
        self.spinBox_TV_X.setObjectName("spinBox_TV_X")
        self.horizontalLayout_30.addWidget(self.spinBox_TV_X)
        self.horizontalSlider_TV_X = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_TV_X.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TV_X.setObjectName("horizontalSlider_TV_X")
        self.horizontalLayout_30.addWidget(self.horizontalSlider_TV_X)
        self.verticalLayout_15.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_56 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color:rgb(0,255,0)")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_31.addWidget(self.label_56)
        self.spinBox_TV_Y = QtWidgets.QSpinBox(self.frame)
        self.spinBox_TV_Y.setObjectName("spinBox_TV_Y")
        self.horizontalLayout_31.addWidget(self.spinBox_TV_Y)
        self.horizontalSlider_TV_Y = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_TV_Y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TV_Y.setObjectName("horizontalSlider_TV_Y")
        self.horizontalLayout_31.addWidget(self.horizontalSlider_TV_Y)
        self.verticalLayout_15.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_57 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color:rgb(0,0,255)")
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_32.addWidget(self.label_57)
        self.spinBox_TV_Z = QtWidgets.QSpinBox(self.frame)
        self.spinBox_TV_Z.setObjectName("spinBox_TV_Z")
        self.horizontalLayout_32.addWidget(self.spinBox_TV_Z)
        self.horizontalSlider_TV_Z = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_TV_Z.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_TV_Z.setObjectName("horizontalSlider_TV_Z")
        self.horizontalLayout_32.addWidget(self.horizontalSlider_TV_Z)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_15.addWidget(self.line_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_13.addWidget(self.frame)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(602, 602))
        self.frame_5.setMaximumSize(QtCore.QSize(602, 602))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_vtkSegment = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_vtkSegment.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_vtkSegment.setObjectName("horizontalLayout_vtkSegment")
        self.label_pictrue = QtWidgets.QLabel(self.frame_5)
        self.label_pictrue.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.label_pictrue.setText("")
        self.label_pictrue.setObjectName("label_pictrue")
        self.horizontalLayout_vtkSegment.addWidget(self.label_pictrue)
        self.verticalLayout_12.addWidget(self.frame_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1667, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_importImage = QtWidgets.QAction(MainWindow)
        self.action_importImage.setObjectName("action_importImage")
        self.action_importLabel = QtWidgets.QAction(MainWindow)
        self.action_importLabel.setObjectName("action_importLabel")
        self.action_display_VLA = QtWidgets.QAction(MainWindow)
        self.action_display_VLA.setObjectName("action_display_VLA")
        self.action_display_LVOT = QtWidgets.QAction(MainWindow)
        self.action_display_LVOT.setObjectName("action_display_LVOT")
        self.action_display_4CH = QtWidgets.QAction(MainWindow)
        self.action_display_4CH.setObjectName("action_display_4CH")
        self.action_display_SAS = QtWidgets.QAction(MainWindow)
        self.action_display_SAS.setObjectName("action_display_SAS")
        self.action_saveCoords = QtWidgets.QAction(MainWindow)
        self.action_saveCoords.setObjectName("action_saveCoords")
        self.action_display_RVOT = QtWidgets.QAction(MainWindow)
        self.action_display_RVOT.setObjectName("action_display_RVOT")
        self.menu.addAction(self.action_importImage)
        self.menu.addAction(self.action_importLabel)
        self.menu.addAction(self.action_saveCoords)
        self.menu_2.addAction(self.action_display_SAS)
        self.menu_2.addAction(self.action_display_VLA)
        self.menu_2.addAction(self.action_display_LVOT)
        self.menu_2.addAction(self.action_display_4CH)
        self.menu_2.addAction(self.action_display_RVOT)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_importImage.triggered.connect(MainWindow.on_importImage)
        self.action_importLabel.triggered.connect(MainWindow.on_importLabel)
        self.action_display_VLA.triggered.connect(MainWindow.on_display_VLA)
        self.action_display_LVOT.triggered.connect(MainWindow.on_display_LVOT)
        self.action_display_4CH.triggered.connect(MainWindow.on_display_4CH)
        self.horizontalScrollBar_spinCenterX_vtk.valueChanged['int'].connect(MainWindow.on_change_spinCenterX_vtk)
        self.horizontalScrollBar_spinCenterY_vtk.valueChanged['int'].connect(MainWindow.on_change_spinCenterY_vtk)
        self.horizontalScrollBar_spinCenterZ_vtk.valueChanged['int'].connect(MainWindow.on_change_spinCenterZ_vtk)
        self.horizontalSlider_AV_X.valueChanged['int'].connect(MainWindow.on_change_AV_X)
        self.horizontalSlider_AV_Y.valueChanged['int'].connect(MainWindow.on_change_AV_Y)
        self.horizontalSlider_AV_Z.valueChanged['int'].connect(MainWindow.on_change_AV_Z)
        self.action_display_SAS.triggered.connect(MainWindow.on_display_SAS)
        self.horizontalSlider_LVA_X.valueChanged['int'].connect(MainWindow.on_change_LVA_X)
        self.horizontalSlider_LVA_Y.valueChanged['int'].connect(MainWindow.on_change_LVA_Y)
        self.horizontalSlider_LVA_Z.valueChanged['int'].connect(MainWindow.on_change_LVA_Z)
        self.horizontalSlider_MV_X.valueChanged['int'].connect(MainWindow.on_change_MV_X)
        self.horizontalSlider_MV_Y.valueChanged['int'].connect(MainWindow.on_change_MV_Y)
        self.horizontalSlider_MV_Z.valueChanged['int'].connect(MainWindow.on_change_MV_Z)
        self.horizontalSlider_PV_X.valueChanged['int'].connect(MainWindow.on_change_PV_X)
        self.horizontalSlider_PV_Y.valueChanged['int'].connect(MainWindow.on_change_PV_Y)
        self.horizontalSlider_PV_Z.valueChanged['int'].connect(MainWindow.on_change_PV_Z)
        self.horizontalSlider_TV_X.valueChanged['int'].connect(MainWindow.on_change_TV_X)
        self.horizontalSlider_TV_Y.valueChanged['int'].connect(MainWindow.on_change_TV_Y)
        self.horizontalSlider_TV_Z.valueChanged['int'].connect(MainWindow.on_change_TV_Z)
        self.horizontalSlider_RVA_X.valueChanged['int'].connect(MainWindow.on_change_RVA_X)
        self.horizontalSlider_RVA_Y.valueChanged['int'].connect(MainWindow.on_change_RVA_Y)
        self.horizontalSlider_RVA_Z.valueChanged['int'].connect(MainWindow.on_change_RVA_Z)
        self.action_saveCoords.triggered.connect(MainWindow.on_saveCoords)
        self.spinBox_LVA_X.valueChanged['int'].connect(MainWindow.on_change_LVA_X)
        self.spinBox_LVA_Y.valueChanged['int'].connect(MainWindow.on_change_LVA_Y)
        self.spinBox_LVA_Z.valueChanged['int'].connect(MainWindow.on_change_LVA_Z)
        self.spinBox_AV_X.valueChanged['int'].connect(MainWindow.on_change_AV_X)
        self.spinBox_AV_Y.valueChanged['int'].connect(MainWindow.on_change_AV_Y)
        self.spinBox_AV_Z.valueChanged['int'].connect(MainWindow.on_change_AV_Z)
        self.spinBox_MV_X.valueChanged['int'].connect(MainWindow.on_change_MV_X)
        self.spinBox_MV_Y.valueChanged['int'].connect(MainWindow.on_change_MV_Y)
        self.spinBox_MV_Z.valueChanged['int'].connect(MainWindow.on_change_MV_Z)
        self.spinBox_RVA_X.valueChanged['int'].connect(MainWindow.on_change_RVA_X)
        self.spinBox_RVA_Y.valueChanged['int'].connect(MainWindow.on_change_RVA_Y)
        self.spinBox_RVA_Z.valueChanged['int'].connect(MainWindow.on_change_RVA_Z)
        self.spinBox_PV_X.valueChanged['int'].connect(MainWindow.on_change_PV_X)
        self.spinBox_PV_Y.valueChanged['int'].connect(MainWindow.on_change_PV_Y)
        self.spinBox_PV_Z.valueChanged['int'].connect(MainWindow.on_change_PV_Z)
        self.spinBox_TV_X.valueChanged['int'].connect(MainWindow.on_change_TV_X)
        self.spinBox_TV_Y.valueChanged['int'].connect(MainWindow.on_change_TV_Y)
        self.spinBox_TV_Z.valueChanged['int'].connect(MainWindow.on_change_TV_Z)
        self.action_display_RVOT.triggered.connect(MainWindow.on_display_RVOT)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_38.setText(_translate("MainWindow", "x:"))
        self.label_39.setText(_translate("MainWindow", "y:"))
        self.label_46.setText(_translate("MainWindow", "z:"))
        self.label_2.setText(_translate("MainWindow", "Image路径："))
        self.label_5.setText(_translate("MainWindow", "Label路径："))
        self.label_16.setText(_translate("MainWindow", "左心底LVA（红）"))
        self.label_34.setText(_translate("MainWindow", "x:"))
        self.label_35.setText(_translate("MainWindow", "y:"))
        self.label_36.setText(_translate("MainWindow", "z:"))
        self.label_17.setText(_translate("MainWindow", "右心底RVA（橙）"))
        self.label_37.setText(_translate("MainWindow", "x:"))
        self.label_40.setText(_translate("MainWindow", "y:"))
        self.label_41.setText(_translate("MainWindow", "z:"))
        self.label_19.setText(_translate("MainWindow", "主动脉瓣AV（黄）"))
        self.label_45.setText(_translate("MainWindow", "x:"))
        self.label_48.setText(_translate("MainWindow", "y:"))
        self.label_50.setText(_translate("MainWindow", "z:"))
        self.label_18.setText(_translate("MainWindow", "肺动脉瓣PV（绿）"))
        self.label_42.setText(_translate("MainWindow", "x:"))
        self.label_43.setText(_translate("MainWindow", "y:"))
        self.label_44.setText(_translate("MainWindow", "z:"))
        self.label_20.setText(_translate("MainWindow", "二尖瓣MV（蓝）"))
        self.label_52.setText(_translate("MainWindow", "x:"))
        self.label_53.setText(_translate("MainWindow", "y:"))
        self.label_54.setText(_translate("MainWindow", "z:"))
        self.label_21.setText(_translate("MainWindow", "三尖瓣TV（紫）"))
        self.label_55.setText(_translate("MainWindow", "x:"))
        self.label_56.setText(_translate("MainWindow", "y:"))
        self.label_57.setText(_translate("MainWindow", "z:"))
        self.menu.setTitle(_translate("MainWindow", "输入输出"))
        self.menu_2.setTitle(_translate("MainWindow", "展示"))
        self.action_importImage.setText(_translate("MainWindow", "导入Image"))
        self.action_importImage.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_importLabel.setText(_translate("MainWindow", "导入Label"))
        self.action_importLabel.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_display_VLA.setText(_translate("MainWindow", "展示垂直长轴维"))
        self.action_display_VLA.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.action_display_LVOT.setText(_translate("MainWindow", "展示左心室流出道"))
        self.action_display_LVOT.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_display_4CH.setText(_translate("MainWindow", "展示4腔心"))
        self.action_display_4CH.setToolTip(_translate("MainWindow", "展示4腔心"))
        self.action_display_4CH.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_display_SAS.setText(_translate("MainWindow", "展示短轴位"))
        self.action_display_SAS.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_saveCoords.setText(_translate("MainWindow", "保存关键点"))
        self.action_saveCoords.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_display_RVOT.setText(_translate("MainWindow", "展示右心室流出道"))
        self.action_display_RVOT.setShortcut(_translate("MainWindow", "Ctrl+B"))

